"""
Generates the analysis figures for each experiment: the training curves
(loss and accuracy per epoch) and the confusion matrix on the test set
"""

import matplotlib

matplotlib.use("Agg") # It does not use the terminal; it only saves to a file

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def plot_training_curves(log_csv_path, save_path):
    """
    Reads the CSV generated by train_supervised.py after each epoch
    (columns: epoch, train_loss, train_acc, val_loss, val_acc, lr, time_s)
    and plots two graphs: loss and accuracy, each showing the training
    and validation curves
    """
    df = pd.read_csv(log_csv_path)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    axes[0].plot(df["epoch"], df["train_loss"], label="train")
    axes[0].plot(df["epoch"], df["val_loss"], label="validation")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].set_title("Training Loss")
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    axes[1].plot(df["epoch"], df["train_acc"], label="train")
    axes[1].plot(df["epoch"], df["val_acc"], label="validation")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy (%)")
    axes[1].set_title("Training Accuracy")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"[visualization.py] Training curves saved to {save_path}")


def plot_confusion_matrix(cm, class_names, save_path, normalize=True):
    """
    Plots the model's confusion matrix on the test set

    normalize=True: each row is expressed as a percentage of the total
    number of samples in the corresponding true class, making classes
    with different numbers of examples directly comparable
    """
    cm = np.array(cm, dtype=np.float64)
    if normalize:
        row_sums = cm.sum(axis=1, keepdims=True)
        cm_display = np.divide(
            cm, row_sums, out=np.zeros_like(cm), where=row_sums != 0
        ) * 100
        fmt = ".1f"
        cbar_label = "% of true class"
    else:
        cm_display = cm
        fmt = ".0f"
        cbar_label = "Number of samples"

    fig, ax = plt.subplots(figsize=(7, 6))
    im = ax.imshow(cm_display, cmap="Blues")
    fig.colorbar(im, ax=ax, label=cbar_label)

    ax.set_xticks(range(len(class_names)))
    ax.set_yticks(range(len(class_names)))
    ax.set_xticklabels(class_names, rotation=45, ha="right")
    ax.set_yticklabels(class_names)
    ax.set_xlabel("Predicted class")
    ax.set_ylabel("True class")
    ax.set_title("Confusion Matrix (Test Set)")

    # Write the value inside each cell, using either white or black text
    # depending on the background intensity to ensure readability
    threshold = cm_display.max() / 2.0 if cm_display.max() > 0 else 1.0
    for i in range(cm_display.shape[0]):
        for j in range(cm_display.shape[1]):
            value = cm_display[i, j]
            ax.text(
                j,
                i,
                format(value, fmt),
                ha="center",
                va="center",
                color="white" if value > threshold else "black",
                fontsize=8,
            )

    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"[visualization.py] Confusion matrix saved to {save_path}")

